[package]
name = "hexatower_app"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
bevy = { version = "0.19", features = ["debug"] }
thiserror = "2.0"
serde = { version = "1", features = ["derive"] }
core_game_logic = { path = ".././core_game_logic" }
ron = "0.12"
bevy_obj = "0.19"
bevy_renet = "5.0.0"

[lints.clippy]
too_many_arguments = "allow"
